# Generated by Django 4.1.3 on 2022-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='calories_consumed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
